apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argo-cd

spec:
  project: default

  source:
    repoURL: https://github.com/zakariyaa4458/eks-project1
    targetRevision: main
    path: kubernetes/argocd/apps

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true