apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-service-service-account
  namespace: application-namespace
  annotations:
     eks.amazonaws.com/role-arn: arn:aws:iam::499024813019:role/inventory-database-secret-role
automountServiceAccountToken: false