apiVersion: v1
kind: ServiceAccount
metadata:
  name: shipping-service-service-account
  namespace: application-namespace
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::499024813019:role/shipping-iam-role
automountServiceAccountToken: false