apiVersion: v1
kind: Service
metadata:
  name:  shipping-service-service
  namespace: application-namespace

spec:
  selector:
    app: shipping-service

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085