apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-service-account
  namespace: application-namespace
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::499024813019:role/worker-iam-role
automountServiceAccountToken: true
  
