apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-service-account
  namespace: database-ns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::499024813019:role/postgres-role
automountServiceAccountToken: false