persistence:
  enabled: true
  size: 10Gi
  storageClassName: ebs-sc

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring-ns.svc.cluster.local
        isDefault: true