apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
  labels:
    app: payment-service
    environment: production
  namespace: application-namespace
  annotations:
    checkov.io/skip1: CKV_K8S_43=I will add commits when I apply the aws infrastructure
    checkov.io/skip2: CKV_K8S_14=I will add commits when I apply the aws infrastructure
    checkov.io/skip3: CKV_K8S_35
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 30000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: payment-service-service-account
      containers:
        - name: payment-service
          image: >-
            499024813019.dkr.ecr.eu-west-2.amazonaws.com/payment-service:78f3ad5f2b8f682a9d805c669b66e22cfa305056-128
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 10000
            runAsGroup: 30000
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8083
          volumeMounts:
            - name: aws-secrets-store
              mountPath: /mnt/secrets-store/application
              readOnly: true
          envFrom:
            - secretRef:
                name: application-secret
            - secretRef:
                name: application-secret-sqs
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 250m
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8083
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: aws-secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: aws-secrets
