apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
    environment: production
  namespace: database-ns
  annotations:
    checkov.io/skip1: CKV_K8S_43=I will add commits when I apply the aws infrastructure
    checkov.io/skip2: CKV_K8S_22=read-only filesystems is not optimal for redis, as it needs to write to disk for persistence

spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 30000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: Always
          securityContext:
            runAsUser: 10000
            runAsGroup: 30000
            seccompProfile:
              type: RuntimeDefault
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
            allowPrivilegeEscalation: false
          
          ports:
          - containerPort: 6379

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"

          livenessProbe:
            exec:
              command:
                - redis-cli 
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2