apiVersion: v1
kind: Secret
metadata:
  name: application-secret
  namespace: application-namespace

type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9hcHA6bG9jYWxkZXZAcG9zdGdyZXMtc2VydmljZS5kYXRhYmFzZS1ucy5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL29yZGVycz9zc2xtb2RlPWRpc2FibGU=