apiVersion: v1
kind: Secret
metadata:
  name: application-secret-sqs
  namespace: application-namespace

type: Opaque
data:
  SQS_QUEUE_URL: aHR0cHM6Ly9zcXMuZXUtd2VzdC0yLmFtYXpvbmF3cy5jb20vNDk5MDI0ODEzMDE5L2Vrc19zcXM=