name: app-cd pipeline
# builds and tags docker images to ecr repos and updates manifests image tags and commits and pushs the manifest change

run-name: app-cd pipeline by ${{ github.actor }}

on:
  workflow_run:
    workflows:
      - ci pipeline
    types:
      - completed
    branches:
      - main
  
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  

jobs:

  prepare:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.tag.outputs.image_tag }}

    steps:
      - name: Determine image tag
        id: tag
        run: |
           if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
           SHA="${{ github.sha }}"
           else
           SHA="${{ github.event.workflow_run.head_sha }}"
           fi

           echo "image_tag=${SHA}-${{ github.run_number }}" >> "$GITHUB_OUTPUT"

  build-push-docker-images:
    needs: prepare
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}


    strategy:
        matrix:
          service:
            - api-gateway
            - dashboard-api
            - inventory-service
            - notification-service
            - order-service
            - payment-service
            - scheduler
            - shipping-service
            - worker

    steps:
              
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.sha || github.event.workflow_run.head_sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
           role-to-assume: arn:aws:iam::499024813019:role/githubs-action-EcrPushRole
           aws-region: eu-west-2

      - name: login to amazon ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image

        run: |
              docker build \
               -t 499024813019.dkr.ecr.eu-west-2.amazonaws.com/${{ matrix.service }}:${{ needs.prepare.outputs.image_tag }} \
               ./services/${{ matrix.service }}


      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: '499024813019.dkr.ecr.eu-west-2.amazonaws.com/${{ matrix.service }}:${{ needs.prepare.outputs.image_tag }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

          
        

      - name: push docker image
        run: |
              docker push \
              499024813019.dkr.ecr.eu-west-2.amazonaws.com/${{ matrix.service }}:${{ needs.prepare.outputs.image_tag }} \
            

          

  update-manifests:
    needs:
      - prepare
      - build-push-docker-images
    runs-on: ubuntu-latest  
 
    outputs:
      manifest_commit_sha: ${{ steps.manifest_commit.outputs.commit_sha }}

    steps:

    - name: checkout
      uses: actions/checkout@v4
      with:
        ref: main
  

    - name: Update the image tag in the relevant Kubernetes Deployment manifest. 
      uses: Charlyzzz/update-k8s-image@v1.7.1
      with:
        manifest-path: kubernetes/application/api-gateway/deployment.yaml
        new-image-tag: ${{ needs.prepare.outputs.image_tag }}
        container-name: api-gateway

    - name: Update the image tag in the relevant Kubernetes Deployment manifest.
      uses: Charlyzzz/update-k8s-image@v1.7.1
      with:
        manifest-path: kubernetes/application/dashboard-api/deployment.yaml
        new-image-tag: ${{ needs.prepare.outputs.image_tag }}
        container-name: dashboard-api

    - name: Check manifest change
      run: |
             grep "image:" kubernetes/application/inventory-service/deployment.yaml
             git diff

    - name: Update the image tag in the relevant Kubernetes Deployment manifest.
      uses: Charlyzzz/update-k8s-image@v1.7.1
      with:
        manifest-path: kubernetes/application/inventory-service/deployment.yaml
        new-image-tag: ${{ needs.prepare.outputs.image_tag }}
        container-name: inventory-service

    - name: Update the image tag in the relevant Kubernetes Deployment manifest.
      uses: Charlyzzz/update-k8s-image@v1.7.1
      with:
        manifest-path: kubernetes/application/notification-service/deployment.yaml
        new-image-tag: ${{ needs.prepare.outputs.image_tag }}
        container-name: notification-service

    - name: Update the image tag in the relevant Kubernetes Deployment manifest.
      uses: Charlyzzz/update-k8s-image@v1.7.1
      with:
        manifest-path: kubernetes/application/order-service/deployment.yaml
        new-image-tag: ${{ needs.prepare.outputs.image_tag }}
        container-name: order-service

    - name: Update the image tag in the relevant Kubernetes Deployment manifest.
      uses: Charlyzzz/update-k8s-image@v1.7.1
      with:
        manifest-path: kubernetes/application/payment-service/deployment.yaml
        new-image-tag: ${{ needs.prepare.outputs.image_tag }}
        container-name: payment-service


    - name: Update the image tag in the relevant Kubernetes Deployment manifest.
      uses: Charlyzzz/update-k8s-image@v1.7.1
      with:
        manifest-path: kubernetes/application/scheduler/deployment.yaml
        new-image-tag: ${{ needs.prepare.outputs.image_tag }}
        container-name: scheduler 

    - name: Update the image tag in the relevant Kubernetes Deployment manifest.
      uses: Charlyzzz/update-k8s-image@v1.7.1
      with:
        manifest-path: kubernetes/application/shipping-service/deployment.yaml
        new-image-tag: ${{ needs.prepare.outputs.image_tag }}
        container-name: shipping-service

    - name: Update the image tag in the relevant Kubernetes Deployment manifest.
      uses: Charlyzzz/update-k8s-image@v1.7.1
      with:
        manifest-path: kubernetes/application/worker/deployment.yaml
        new-image-tag: ${{ needs.prepare.outputs.image_tag }}
        container-name: worker

    - name: setting up gitHub then creating git commit and pushing it to gitHub
      id: manifest_commit
      run: |
          git config --global user.email "zakariya.a4458@gmail.com"
          git config --global user.name "zakariyaa4458"
          git add kubernetes/
          git commit -m "new commits for updated manifests"
          echo "commit_sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
          git push

  Rollback-Steps:
    needs: update-manifests
    runs-on: ubuntu-latest

    steps:

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::499024813019:role/github-eks-rollout
        aws-region: eu-west-2

    - name: Configure kubectl
      run: |
         aws eks update-kubeconfig \
         --region eu-west-2 \
         --name eks-cluster

    - name: Wait for ArgoCD
      run: sleep 45
  
    - name: Verify rollout
      id: rollout
      continue-on-error: true
      run: |
            kubectl rollout status deployment/api-gateway-deployment -n application-namespace --timeout=3m
            kubectl rollout status deployment/dashboard-api-deployment -n application-namespace --timeout=3m
            kubectl rollout status deployment/inventory-service-deployment -n application-namespace --timeout=3m
            kubectl rollout status deployment/notification-service-deployment -n application-namespace --timeout=3m
            kubectl rollout status deployment/order-service-deployment -n application-namespace --timeout=3m
            kubectl rollout status deployment/payment-service-deployment -n application-namespace --timeout=3m
            kubectl rollout status deployment/scheduler-deployment -n application-namespace --timeout=3m
            kubectl rollout status deployment/shipping-service-deployment -n application-namespace --timeout=3m
            kubectl rollout status deployment/worker-deployment -n application-namespace --timeout=3m

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0

    - name: Configure Git
      if: steps.rollout.outcome == 'failure'
      run: |
          git config user.email "zakariya.a4458@gmail.com"
          git config user.name "zakariyaa4458"

    - name: Rollback failed deployment
      if: steps.rollout.outcome == 'failure'
      run: |
            git revert --no-edit ${{ needs.update-manifests.outputs.manifest_commit_sha }}
            git push origin main