name: ci pipeline

run-name: CI Pipeline triggered by ${{ github.actor }}

on:
  push:
    branches:
      - main


    paths:
    - Dockerfile
    - services/**
    - kubernetes/**

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  application-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: 
          - api-gateway
          - dashboard-api
          - inventory-service
          - notification-service
          - order-service
          - payment-service
          - scheduler
          - shipping-service
          - worker

    defaults:
        run:
          working-directory: services/${{ matrix.service }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v7
        with:
          go-version: '1.25'

      - name: install dependencies
        run: go mod download

      - name: run tests
        run: go test ./...

      - name: build application
        run: go build

  kubernetes-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Kubernetes Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: kubernetes
        framework: kubernetes
        skip_check: CKV_K8S_43,CKV_K8S_14, 
            

   







