name: ci pipeline

run-name: CI Pipeline triggered by ${{ github.actor }}

on:
  push:
    branches:
      - main


    paths:
    - Dockerfile
    - terraform/**
    - services/**

  workflow_dispatch:

    


permissions:
  id-token: write
  contents: read

jobs:
  application-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: 
          - api-gateway
          - dashboard-api
          - inventory-service
          - notification-service
          - order-service
          - payment-service
          - scheduler
          - shipping-service
          - worker

    defaults:
        run:
          working-directory: services/${{ matrix.service }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v7
        with:
          go-version: '1.25'

      - name: install dependencies
        run: go mod download

      - name: run tests
        run: go test ./...

      - name: build application
        run: go build


  terraform-check:
    runs-on: ubuntu-latest

    defaults:
      run:
       working-directory: terraform

    steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: configure aws
          uses: aws-actions/configure-aws-credentials@v4

          with:
            role-to-assume: arn:aws:iam::499024813019:role/githubs-action-terraformrole
            aws-region: eu-west-2


        - name: setup terraform
          uses: hashicorp/setup-terraform@v4
          with: 
            terraform_version: 1.10.0

        - name: terraform-init
          run: terraform init

        - name: terraform-fmt
          run: terraform fmt -check

        - name: setup tflint
          uses: terraform-linters/setup-tflint@v4

        - name: run tflint
          run: tflint


        - name: run checkov
          uses: bridgecrewio/checkov-action@master
        
        
          with:
            hard_fail_on: CKV_AWS_103,CKV2_AWS_74,CKV2_AWS_12,CKV2_AWS_260,CKV2_AWS_129

        - name: terraform-validate
          run: terraform validate

        - name: terraform-plan
          run: terraform plan -out=tfplan
    
        - name: change it to readable txt
          run: terraform show -no-color tfplan > readable-plan1.txt

        - name: Upload Terraform Plan
          uses: actions/upload-artifact@v4
          with:
            name: tfplan
            path: tfplan

        - name: Upload Terraform Plan
          uses: actions/upload-artifact@v4
          with:
            name: readable-plan1.txt
            path: readable-plan1.txt
            

   







