name: infrastrucuture pipeline 

run-name: infrastructure Pipeline triggered by ${{ github.actor }}

on:
  workflow_run:
    workflows:
      - ci pipeline
    types:
      - completed
    branches:
      - main

permissions:
  id-token: write
  contents: read
  actions: read

jobs:  
  terraform-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: downloading tf plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: downloaded-tfplan
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: downloading tf plan
        uses: actions/download-artifact@v4
        with:
          name: readable-plan1.txt
          path: downloaded-readable-plan1.txt
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v4

        with:
          role-to-assume: arn:aws:iam::499024813019:role/terraform_aws
          aws-region: eu-west-2
  

      - name: terraform setup
        uses: hashicorp/setup-terraform@v4
        with: 
            terraform_version: 1.10.0

      - name: terraform-init
        run: terraform init

      - name: terraform apply
        run: |
               terraform apply ./downloaded-tfplan/tfplan -auto-approve


