apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-secret-provider
  namespace: database-ns
  labels:
    serviceAccountName: postgres-service-account
spec:
  provider: aws                             
  parameters:
    objects: |
      - objectName: "eks/postgres"
        objectType: "secretsmanager"        
        jmespath:
          - path: "POSTGRES_PASSWORD"
            objectAlias: "POSTGRES_password"                      
  secretObjects:                             
    - secretName: "postgres-secret"         
      type: Opaque
      data:
        - objectName: "POSTGRES_password"
          key: "POSTGRES_PASSWORD"
