apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: traefik-ns
spec:
  tls:
  - hosts:
      - api.ecommerce.zakariyaalab.com
    secretName: api-gateway-tls
  rules:
  - host: "api.ecommerce.zakariyaalab.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: api-gateway-service
            port:
              number: 80
  ingressClassName: traefik

  

